INSERT INTO
    students (
        student_id,
        name,
        age,
        major,
        avatar_url,
        attendance,
        absence,
        late
    )
VALUES (
        '2025010',
        'stu_001',
        '18',
        'cs',
        'https://example.2025001.com',
        1,
        1,
        0
    ),
    (
        '2025011',
        'stu_002',
        '18',
        'cs',
        'https://example.002.com',
        1,
        2,
        0
    ),
    (
        '2025012',
        'stu_3',
        '18',
        'cs',
        'https://example.com',
        2,
        2,
        0
    ),
    (
        '2025013',
        'stu_4',
        '18',
        'cs',
        'https://example.com',
        3,
        4,
        0
    ),
    (
        '20250014',
        'stu_5',
        '18',
        'cs',
        'https://example.com',
        5,
        6,
        0
    ),
    (
        '20250015',
        'stu_6',
        '18',
        'cs',
        'https://example.com',
        7,
        8,
        0
    ),
    (
        '2025017',
        'stu_6',
        '18',
        'cs',
        'https://example.com',
        1,
        1,
        0
    );